//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoInvasion.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Photo
    {
        public Photo()
        {
            this.Rating = new HashSet<Rating>();
        }
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int UserId { get; set; }
        public int AlbumId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Views { get; set; }
        public string Source { get; set; }
        public string Description { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Category Category { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Rating> Rating { get; set; }
    }
}
