//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoInvasion.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int PhotoId { get; set; }
        public int UserId { get; set; }
        public int Rating1 { get; set; }
        public byte Seen { get; set; }
        public string Id { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
