//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoInvasion.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Album = new HashSet<Album>();
            this.Photo = new HashSet<Photo>();
            this.Rating = new HashSet<Rating>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Description { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Album> Album { get; set; }
        public virtual ICollection<Photo> Photo { get; set; }
        public virtual ICollection<Rating> Rating { get; set; }
    }
}
